server:
  port: 8888
  
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shiva-sondakar/shopping-cart-config.git
          search-paths: /*          